### ISSUE TITLE
mixed use of $Script:Client_secret and $Script:ClientSecret

### ISSUE THREAD

**Issue by alexrgreenwood** [jhoneill/MSGraphAPI#5]
Hi James 
I couldn't get the -isapp parameter to work until i replaced some instances of **$Script:Client_secret** in Authentication .ps1, it started working when i replaced it with **$Script:ClientSecret** (on line 230)

happy to do the PR if you agree that its a problem , just thought i would check first

**Comment by jhoneill** [comment]
Thanks. Not sure how that slipped through, but yes, if you have code to fix it please send a PR.
