### ISSUE TITLE
authorizationInfo error

### ISSUE THREAD

**Issue by jd0000** [jhoneill/MSGraphAPI#9]
Started receiving error about "authorizationInfo" 
TerminatingError(New-Object): "The member "authorizationInfo" was not found for the specified .NET object."
New-Object : The member "authorizationInfo" was not found for the specified .NET object.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.PlusPlus\1.5.1\Users.ps1:19 char:29
+ ...     $mgr  = New-Object -TypeName MicrosoftGraphUser -Property $r.mana ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.NewObjectCommand

**Temp fix was: Edited Users.ps1 line 18 to: $null = $r.manager.remove('@odata.type'),$r.manager.remove('@odata.id'),$r.manager.remove('authorizationInfo')**

**Comment by jhoneill** [comment]
Sounds like a property has been removed from an object without realising doing so was a breaking change. I'll investigate when I get a moment. Thanks for reporting.
